version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: etms
      MYSQL_PASSWORD: manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .                  # Builds from your Dockerfile in the current directory
    image: my-spring-app        # Explicitly set the image name
    container_name: spring_boot_backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/etms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=manager
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
